In [ ]:
練習問題 5-4 のデータ sample_multi_array_data2 の最大値、最小値、合計値、平均値を求めてください。

In [1]:
import numpy as np

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print("sample_multi_array_data2")
print(sample_multi_array_data2)

print("最大値",sample_multi_array_data2.max())
print("最小値",sample_multi_array_data2.min())
print("合計値",sample_multi_array_data2.sum())
print("平均値",sample_multi_array_data2.mean())


sample_multi_array_data2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
最大値 15
最小値 0
合計値 120
平均値 7.5
