chap-02-Ex-04と同じ行列について、逆行列、固有値と固有ベクトルを求めよ。

In [1]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [1, 3, 2],
    [3, 1, 2]
])

A_inv = np.linalg.inv(A)

print(A_inv)
eigenvalues, eigenvectors = np.linalg.eig(A)

print("固有値:")
print(eigenvalues)

print("固有ベクトル:")
print(eigenvectors)


[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値:
[ 6.         -1.41421356  1.41421356]
固有ベクトル:
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]
