以下の行列に対して、特異値分解をしてください。

In [4]:
import numpy as np
from scipy import linalg

np.set_printoptions(precision=3, suppress=True)

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print("B:")
print(B)
print("B.shape:", B.shape)

U, s, Vh = linalg.svd(B)
print("U:", U)
print("s:", s)
print("Vh:", Vh)

m, n = B.shape
S = linalg.diagsvd(s, m, n)

print("S:", S)

B_reconstructed = U @ S @ Vh
print("B_reconstructed:", B_reconstructed)




B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
B.shape: (4, 3)
U: [[-0.141 -0.825  0.547 -0.027]
 [-0.344 -0.426 -0.709  0.444]
 [-0.547 -0.028 -0.223 -0.806]
 [-0.75   0.371  0.385  0.39 ]]
s: [25.462  1.291  0.   ]
Vh: [[-0.505 -0.575 -0.644]
 [ 0.761  0.057 -0.646]
 [-0.408  0.816 -0.408]]
S: [[25.462  0.     0.   ]
 [ 0.     1.291  0.   ]
 [ 0.     0.     0.   ]
 [ 0.     0.     0.   ]]
B_reconstructed: [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
