以下のデータに対して、すべての要素の平方根を計算した行列を表示してください。

In [2]:
import numpy as np

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print("sample_multi_array_data2")
print(sample_multi_array_data2)

answer_5_4 = np.sqrt(sample_multi_array_data2)
print("answer_5_4")
print(answer_5_4)

sample_multi_array_data2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
answer_5_4
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]]
