要素がすべて3の5行5列の行列を作成し、その行列を2乗する計算をする。

In [1]:
import numpy as np

A = np.full((5,5),3)

B = A ** 2

print(A)
print(B)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
