以下の行列に対して、LU分解をして、Ax = b の方程式を解いてください。

In [6]:
import numpy as np
from scipy import linalg

A = np.identity(3)
A[0, :] = 1
A[:, 0] = 1
A[0, 0] = 3

b = np.ones(3)

print("A:")
print(A)

print("b:")
print(b)

LU,piv = linalg.lu_factor(A)

x = linalg.lu_solve((LU, piv), b)
print("x:")
print(x)

print("A @ x:")
print(A @ x)


A:
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
b:
[1. 1. 1.]
x:
[-1.  2.  2.]
A @ x:
[1. 1. 1.]
