次の2つの配列を縦に結合しなさい。

In [1]:
import numpy as np

sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

answer_5_7 = np.hstack((sample_array1, sample_array2))
print(answer_5_7)


[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
