In [ ]:
練習問題 5-4 のデータ sample_multi_array_data2 の対角成分の和を求めてください。

In [1]:
import numpy as np

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print("sample_multi_array_data2")
print(sample_multi_array_data2)

print("対角成分の和", np.trace(sample_multi_array_data2))

sample_multi_array_data2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
対角成分の和 30
