sample_names が 'c' ではない data を取り出しなさい。

In [7]:
import numpy as np
import numpy.random as random

sample_name = np.array(['a', 'b', 'c', 'd', 'a'])

random.seed(0)
data = random.randn(5,5)

print("sample_name")
print(sample_name)

print("data")
print(data)

answer_5_2 = data[sample_name != 'c']
print("answer_5_2")
print(answer_5_2)



sample_name
['a' 'b' 'c' 'd' 'a']
data
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]
answer_5_2
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]
